# Generated by Django 5.2.3 on 2025-06-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'معاملة', 'verbose_name_plural': 'المعاملات'},
        ),
    ]
