# Generated by Django 5.2.3 on 2025-06-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'تقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
    ]
