# Generated by Django 5.2.3 on 2025-06-19 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='0500000000', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام', regex='^05\\d{8}$')], verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True, verbose_name='اسم المستخدم'),
            preserve_default=False,
        ),
    ]
